PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE access_token ( id INTEGER PRIMARY KEY AUTOINCREMENT, access_token TEXT NOT NULL, expire_time INTEGER DEFAULT 0);
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,open_id CHAR(56) NOT NULL,key CHAR(32) NOT NULL,status TINYINT DEFAULT 1);
COMMIT;
